---
sidebar: sidebar 
permalink: use-acp/acp-snap-restore.html 
keywords: snapshot restore, snapshot, astra control provisioner, TridentActionSnapshotRestore, 
summary: 'Astra Control Provivisioner esegue un ripristino rapido e in-place dei volumi da uno snapshot utilizzando `TridentActionSnapshotRestore` (TASR) CR. Questo CR funziona come un"azione imperativa di Kubernetes e non persiste al termine dell"operazione.' 
---
= Ripristina i dati dei volumi utilizzando uno snapshot
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/use/


[role="lead"]
Astra Control Provivisioner esegue un ripristino rapido e in-place dei volumi da uno snapshot utilizzando `TridentActionSnapshotRestore` (TASR) CR. Questo CR funziona come un'azione imperativa di Kubernetes e non persiste al termine dell'operazione.

Astra Control provisioner supporta il ripristino delle snapshot su `ontap-san`, `ontap-san-economy`, `ontap-nas`, `ontap-nas-flexgroup`, `azure-netapp-files`, `gcp-cvs`, e. `solidfire-san` driver.

.Prima di iniziare
È necessario disporre di un PVC associato e di uno snapshot del volume disponibile.

* Verificare che lo stato del PVC sia limitato.
+
[listing]
----
kubectl get pvc
----
* Verificare che lo snapshot del volume sia pronto per l'uso.
+
[listing]
----
kubectl get vs
----


.Fasi
. Creare TASR CR. In questo esempio viene creato un CR per PVC `pvc1` e snapshot del volume `pvc1-snapshot`.
+
[listing]
----
cat tasr-pvc1-snapshot.yaml

apiVersion: v1
kind: TridentActionSnapshotRestore
metadata:
  name: this-doesnt-matter
  namespace: trident
spec:
  pvcName: pvc1
  volumeSnapshotName: pvc1-snapshot
----
. Applicare la CR per eseguire il ripristino dall'istantanea. In questo esempio vengono ripristinati gli snapshot `pvc1`.
+
[listing]
----
kubectl create -f tasr-pvc1-snapshot.yaml

tridentactionsnapshotrestore.trident.netapp.io/this-doesnt-matter created
----


.Risultati
Astra Control Provivisioner ripristina i dati dalla snapshot. È possibile verificare lo stato di ripristino dello snapshot.

[listing]
----
kubectl get tasr -o yaml

apiVersion: v1
items:
- apiVersion: trident.netapp.io/v1
  kind: TridentActionSnapshotRestore
  metadata:
    creationTimestamp: "2023-04-14T00:20:33Z"
    generation: 3
    name: this-doesnt-matter
    namespace: trident
    resourceVersion: "3453847"
    uid: <uid>
  spec:
    pvcName: pvc1
    volumeSnapshotName: pvc1-snapshot
  status:
    startTime: "2023-04-14T00:20:34Z"
    completionTime: "2023-04-14T00:20:37Z"
    state: Succeeded
kind: List
metadata:
  resourceVersion: ""
----
[NOTE]
====
* Nella maggior parte dei casi, Astra Control provisioner non ritenta automaticamente l'operazione in caso di guasto. Sarà necessario eseguire nuovamente l'operazione.
* Gli utenti Kubernetes senza accesso amministrativo potrebbero dover essere autorizzati dall'amministratore a creare una TASR CR nel namespace delle applicazioni.


====