---
sidebar: sidebar 
permalink: use/manage-credentials.html 
keywords: invite users, add users, remove users, delete users 
summary: 'Aggiungi e rimuovi le credenziali del cloud provider dal tuo account in qualsiasi momento. Astra Control utilizza queste credenziali per il provisioning delle risorse per conto dell"utente.' 
---
= Aggiungere e rimuovere le credenziali
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/use/


[role="lead"]
Aggiungi e rimuovi le credenziali del cloud provider dal tuo account in qualsiasi momento. Astra Control utilizza queste credenziali per rilevare un cluster Kubernetes, le applicazioni sul cluster e per eseguire il provisioning delle risorse per conto dell'utente.

Tutti gli utenti di Astra Control condividono gli stessi set di credenziali.



== Aggiungere credenziali

Il metodo più comune per aggiungere credenziali ad Astra Control consiste nella gestione dei cluster, ma è anche possibile aggiungere credenziali dalla pagina account. Le credenziali saranno quindi disponibili per la gestione di cluster Kubernetes aggiuntivi.

.Prima di iniziare
ifdef::aws[]

* Per Amazon Web Services, è necessario disporre dell'output JSON delle credenziali dell'account IAM utilizzato per creare il cluster. link:../get-started/set-up-amazon-web-services.html["Scopri come configurare un utente IAM"].


endif::aws[]

ifdef::gcp[]

* Per GKE, è necessario disporre del file della chiave dell'account di servizio per un account di servizio che dispone delle autorizzazioni necessarie. link:../get-started/set-up-google-cloud.html["Scopri come configurare un account di servizio"].


endif::gcp[]

ifdef::azure[]

* Per AKS, è necessario disporre del file JSON che contiene l'output dell'interfaccia CLI di Azure al momento della creazione dell'entità del servizio. link:../get-started/set-up-microsoft-azure-with-anf.html["Scopri come configurare un service principal"].
+
Avrai inoltre bisogno del tuo ID di abbonamento Azure, se non lo hai aggiunto al file JSON.



endif::azure[]

.Fasi
. Selezionare *account > credenziali*.
. Selezionare *Aggiungi credenziali*.


ifdef::azure[]

. Selezionare *Microsoft Azure*.


endif::azure[]

ifdef::gcp[]

. Selezionare *Google Cloud Platform*.


endif::gcp[]

ifdef::aws[]

. Selezionare *Amazon Web Services*.


endif::aws[]

. Immettere un nome per le credenziali che le distinguano dalle altre in Astra Control.
. Fornire le credenziali richieste.


ifdef::azure[]

. *Microsoft Azure*: Fornisci ad Astra Control i dettagli sull'entità del servizio Azure caricando un file JSON o incollando il contenuto del file JSON dagli Appunti.
+
Il file JSON deve contenere l'output dell'interfaccia CLI di Azure al momento della creazione dell'entità del servizio. Può anche includere il tuo ID di abbonamento in modo che venga aggiunto automaticamente ad Astra Control. In caso contrario, è necessario inserire manualmente l'ID dopo aver fornito il codice JSON.



endif::azure[]

ifdef::gcp[]

. *Google Cloud Platform*: Fornire il file delle chiavi dell'account del servizio Google Cloud caricando il file o incollando il contenuto dagli Appunti.


endif::gcp[]

ifdef::aws[]

. *Amazon Web Services*: Fornisci le credenziali utente IAM di Amazon Web Services caricando il file o incollando il contenuto dagli Appunti.


endif::aws[]

. Selezionare *Aggiungi credenziali*.


.Risultato
Le credenziali sono ora disponibili per la selezione quando si aggiunge un cluster ad Astra Control.



== Rimuovere le credenziali

Rimuovere le credenziali da un account in qualsiasi momento. Rimuovere le credenziali solo dopo link:unmanage.html["annullamento della gestione di tutti i cluster"], a meno che non si stiano ruotando le credenziali (fare riferimento a. <<Ruotare le credenziali>>).


NOTE: Il primo set di credenziali aggiunto ad Astra Control è sempre in uso perché Astra Control utilizza le credenziali per l'autenticazione nel bucket di backup. Si consiglia di non rimuovere queste credenziali.

.Fasi
. Selezionare *account > credenziali*.
. Selezionare l'elenco a discesa nella colonna *Stato* per le credenziali che si desidera rimuovere.
. Selezionare *Rimuovi*.
. Digitare il nome delle credenziali per confermare l'eliminazione, quindi selezionare *Sì, Rimuovi credenziali*.


.Risultato
Astra Control rimuove le credenziali dall'account.



== Ruotare le credenziali

È possibile ruotare le credenziali nell'account. Se si ruotano le credenziali, ruotarle durante una finestra di manutenzione quando non sono in corso backup (pianificati o on-demand).

.Fasi
. Rimuovere le credenziali esistenti seguendo la procedura descritta in <<Rimuovere le credenziali>>.
. Aggiungere le nuove credenziali seguendo la procedura descritta in <<Aggiungere credenziali>>.
. Aggiorna tutti i bucket per utilizzare le nuove credenziali:
+
.. Dalla barra di navigazione a sinistra, selezionare *Bucket*.
.. Selezionare l'elenco a discesa nella colonna *azioni* per il bucket che si desidera modificare.
.. Selezionare *Modifica*.
.. Nella sezione *Select credentials* (Seleziona credenziali), scegliere le nuove credenziali aggiunte ad Astra Control.
.. Selezionare *Aggiorna*.
.. Ripetere i passaggi da *b* a *e* per tutti i bucket rimanenti sul sistema.




.Risultato
Astra Control inizia a utilizzare le nuove credenziali del cloud provider.
