---
sidebar: sidebar 
permalink: get-started/intro.html 
keywords: introduction, how astra works, how Astra works, what Astra is, concept, understanding, overview 
summary: Astra Control è una soluzione per la gestione del ciclo di vita dei dati delle applicazioni Kubernetes che semplifica le operazioni per le applicazioni stateful. Proteggi, esegui il backup e migra facilmente i carichi di lavoro Kubernetes e crea istantaneamente cloni applicativi funzionanti. 
---
= Scopri di più su Astra Control
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/get-started/


[role="lead"]
Astra Control è una soluzione per la gestione del ciclo di vita dei dati delle applicazioni Kubernetes che semplifica le operazioni per le applicazioni stateful. Proteggi, esegui il backup e migra facilmente i carichi di lavoro Kubernetes e crea istantaneamente cloni applicativi funzionanti.



== Caratteristiche

Astra Control offre funzionalità critiche per la gestione del ciclo di vita dei dati delle applicazioni Kubernetes:

* Gestire automaticamente lo storage persistente
* Creazione di snapshot e backup on-demand basati sulle applicazioni
* Automatizzare le operazioni di backup e snapshot basate su policy
* Migrare applicazioni e dati da un cluster Kubernetes a un altro
* Clonare un'applicazione dallo staging alla produzione
* Visualizzare lo stato di salute e protezione dell'applicazione
* Utilizzare un'interfaccia utente Web o un'API per implementare i flussi di lavoro di backup e migrazione




== Modelli di implementazione

Astra Control è disponibile in due modelli di implementazione:

* *Astra Control Service*: Un servizio gestito da NetApp che offre la gestione dei dati application-aware dei cluster Kubernetes in ambienti di cloud provider multipli, oltre ai cluster Kubernetes autogestiti.
* *Astra Control Center*: Software autogestito che fornisce la gestione dei dati applicativa dei cluster Kubernetes in esecuzione nel tuo ambiente on-premise. Il centro di controllo Astra può essere installato anche in ambienti di cloud provider multipli con un backend di storage NetApp Cloud Volumes ONTAP.


[cols="1h,2d,2a"]
|===
|  | Servizio di controllo Astra | Centro di controllo Astra 


| Come viene offerto? | Come servizio cloud completamente gestito da NetApp  a| 
Come software che puoi scaricare, installare e gestire



| Dove è ospitato? | Su un cloud pubblico scelto da NetApp  a| 
Sul tuo cluster Kubernetes



| Come viene aggiornato? | Gestito da NetApp  a| 
Gli aggiornamenti vengono gestiti



| Quali sono i backend di storage supportati?  a| 
* Servizi Web Amazon:
+
** Amazon EBS
** Amazon FSX per NetApp ONTAP
** https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-getting-started-aws.html["Cloud Volumes ONTAP"^]




endif::aws[]

ifdef::gcp[]

* Google Cloud:
+
** Disco persistente di Google
** NetApp Cloud Volumes Service
** https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-getting-started-gcp.html["Cloud Volumes ONTAP"^]




endif::gcp[]

ifdef::azure[]

* Microsoft Azure:
+
** Dischi gestiti Azure
** Azure NetApp Files
** https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-getting-started-azure.html["Cloud Volumes ONTAP"^]




endif::azure[]

* Cluster a gestione automatica:
+
** Amazon EBS
** Disco persistente di Google
** Dischi gestiti Azure
** https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/["Cloud Volumes ONTAP"^]


* Cluster on-premise:
+
** Sistemi NetApp ONTAP AFF e FAS
** NetApp ONTAP Select
** Cloud Volumes ONTAP



 a| 
* Sistemi NetApp ONTAP AFF e FAS
* NetApp ONTAP Select
* https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/["Cloud Volumes ONTAP"^]


|===


== Come funziona Astra Control Service

Astra Control Service è un servizio cloud gestito da NetApp sempre attivo e aggiornato con le funzionalità più recenti. Utilizza diversi componenti per consentire la gestione del ciclo di vita dei dati delle applicazioni.

Ad alto livello, Astra Control Service funziona come segue:

* Per iniziare a utilizzare Astra Control Service, devi configurare il tuo cloud provider e registrarti per un account Astra.


ifdef::gcp[]

+ ** per i cluster GKE, Astra Control Service utilizza https://cloud.netapp.com/cloud-volumes-service-for-gcp["NetApp Cloud Volumes Service per Google Cloud"^] O Google Persistent Disks come back-end di storage per i volumi persistenti.

endif::gcp[]

ifdef::azure[]

+ ** per i cluster AKS, Astra Control Service utilizza https://cloud.netapp.com/azure-netapp-files["Azure NetApp Files"^] O Azure Managed Disks come back-end di storage per i volumi persistenti.

endif::azure[]

ifdef::aws[]

+ ** per i cluster Amazon EKS, Astra Control Service utilizza https://docs.aws.amazon.com/ebs/["Amazon Elastic Block Store"^] oppure https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/what-is-fsx-ontap.html["Amazon FSX per NetApp ONTAP"^] come back-end di storage per i volumi persistenti.

endif::aws[]

* Aggiungi il tuo primo calcolo Kubernetes ad Astra Control Service. Astra Control Service esegue le seguenti operazioni:
+
** Crea un archivio di oggetti nel tuo account cloud provider, dove vengono memorizzate le copie di backup.




ifdef::azure[]

In Azure, Astra Control Service crea anche un gruppo di risorse, un account di storage e chiavi per il container Blob.

endif::azure[]

* Crea un nuovo ruolo di amministratore e un nuovo account del servizio Kubernetes sul cluster.
* Utilizza il nuovo ruolo di amministratore per l'installazione https://docs.netapp.com/us-en/trident/index.html["Astra Trident"^] sul cluster e per creare una o più classi di storage.
* Se utilizzi un'offerta di cloud service storage NetApp come back-end dello storage, Astra Control Service utilizza Astra Trident per eseguire il provisioning di volumi persistenti per le tue applicazioni. Se si utilizzano dischi gestiti Amazon EBS o Azure come back-end dello storage, è necessario installare un driver CSI specifico del provider. Le istruzioni di installazione sono fornite in link:set-up-amazon-web-services.html["Configurare Amazon Web Services"^] e. link:set-up-microsoft-azure-with-amd.html["Configurare Microsoft Azure con dischi gestiti Azure"^].
+
** A questo punto, è possibile definire le applicazioni dal cluster. Il provisioning dei volumi persistenti sul back-end dello storage viene eseguito attraverso la nuova classe di storage predefinita.
** Quindi, utilizza Astra Control Service per gestire queste applicazioni e iniziare a creare snapshot, backup e cloni.




Il piano gratuito di Astra Control ti consente di gestire fino a 10 spazi dei nomi nel tuo account. Se si desidera gestire più di 10 spazi dei nomi, è necessario impostare la fatturazione eseguendo l'aggiornamento dal piano gratuito al piano Premium.



== Come funziona Astra Control Center

Astra Control Center viene eseguito localmente nel tuo cloud privato.

Centro di controllo Astra supporta cluster Kubernetes con classe di storage basata su Trident con un backend di storage ONTAP 9.5 e superiore.

In un ambiente connesso al cloud, Astra Control Center utilizza Cloud Insights per fornire monitoraggio e telemetria avanzati. In assenza di una connessione Cloud Insights, il monitoraggio e la telemetria sono disponibili in un centro di controllo Astra per un periodo di 7 giorni ed esportati anche in strumenti di monitoraggio nativi Kubernetes (come Prometheus e Grafana) attraverso endpoint di metriche aperte.

Il centro di controllo Astra è completamente integrato nell'ecosistema AutoSupport e Active IQ per fornire agli utenti e al supporto NetApp informazioni sulla risoluzione dei problemi e sull'utilizzo.

Puoi provare Astra Control Center utilizzando una licenza di valutazione di 90 giorni. La versione di valutazione è supportata tramite e-mail e opzioni della community. Inoltre, puoi accedere agli articoli e alla documentazione della Knowledge base dalla dashboard di supporto all'interno del prodotto.

Per installare e utilizzare Astra Control Center, è necessario soddisfare determinati requisiti https://docs.netapp.com/us-en/astra-control-center/get-started/requirements.html["requisiti"].

Ad alto livello, Astra Control Center funziona come segue:

* Astra Control Center viene installato nel proprio ambiente locale. Scopri di più su come https://docs.netapp.com/us-en/astra-control-center/get-started/install_acc.html["Installare Astra Control Center"].
* È possibile completare alcune attività di configurazione, come ad esempio:
+
** Impostare la licenza.
** Aggiungere il primo cluster.
** Aggiungere il backend di storage rilevato quando si aggiunge il cluster.
** Aggiungi un bucket di store di oggetti che memorizzerà i backup delle tue app.




Scopri di più su come https://docs.netapp.com/us-en/astra-control-center/get-started/setup_overview.html["Configurare Astra Control Center"].

È possibile aggiungere applicazioni al cluster. In alternativa, se nel cluster gestito sono già presenti alcune applicazioni, è possibile utilizzare Astra Control Center per gestirle. Quindi, utilizza Astra Control Center per creare snapshot, backup, cloni e relazioni di replica.



== Per ulteriori informazioni

* https://docs.netapp.com/us-en/astra-family/["Documentazione per la famiglia di prodotti NetApp Astra"^]
* https://docs.netapp.com/us-en/astra/index.html["Documentazione del servizio Astra Control"^]
* https://docs.netapp.com/us-en/astra-control-center/index.html["Documentazione di Astra Control Center"^]
* https://docs.netapp.com/us-en/trident/index.html["Documentazione di Astra Trident"^]
* https://docs.netapp.com/us-en/astra-automation/index.html["Utilizzare l'API di controllo Astra"^]
* https://docs.netapp.com/us-en/cloudinsights/["Documentazione Cloud Insights"^]
* https://docs.netapp.com/us-en/ontap/index.html["Documentazione ONTAP"^]

