---
sidebar: sidebar 
permalink: get-started/manage-private-cluster.html 
keywords: discover private cluster, add cluster, add kubernetes cluster, private, discover kubernetes cluster, add private cluster 
summary: 'Dopo aver configurato l"ambiente, è possibile creare un cluster Kubernetes e aggiungerlo ad Astra Control Service.' 
---
= Gestire i cluster privati da Astra Control Service
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/get-started/


[role="lead"]
Puoi utilizzare Astra Control Service per gestire cluster privati Azure Kubernetes Service (AKS) e cluster privati Red Hat OpenShift in AKS. Queste istruzioni presuppongono che sia già stato creato un cluster AKS o OpenShift privato e che sia stato preparato un metodo sicuro per accedervi in remoto; per ulteriori informazioni sulla creazione e l'accesso a cluster AKS o OpenShift privati, fare riferimento alla seguente documentazione:

* https://docs.microsoft.com/azure/aks/private-clusters["Documentazione di Azure per cluster AKS privati"^]
* https://learn.microsoft.com/en-us/azure/openshift/howto-create-private-cluster-4x["Documentazione di Azure per cluster OpenShift privati"^]




== Installare l'operatore del connettore Astra

È necessario installare l'operatore Astra Connector sul cluster privato. Se si utilizza un host Bastion, eseguire questi comandi dalla riga di comando dell'host Bastion.

.Fasi
. Clonare il repository GitHub dell'operatore Astra Connector:
+
[source, console]
----
git clone https://github.com/NetApp/astra-connector-operator.git
----
. Modificare le directory al livello superiore del pacchetto operatore decompresso, in modo da visualizzare `astraconnector_operator.yaml` file con `ls` comando.
. Creare uno spazio dei nomi per l'operatore Astra Connector.
+
[source, console]
----
kubectl create ns astra-connector-operator
----
. Applicare il `astraconnector_operator.yaml` nel namespace dell'operatore.
+
[source, console]
----
kubectl apply -f astraconnector_operator.yaml -n astra-connector-operator
----
. Creare uno spazio dei nomi per i componenti del cluster privato.
+
[source, console]
----
kubectl create ns astra-connector
----
. Generare un token API Astra Control seguendo le istruzioni contenute in https://docs.netapp.com/us-en/astra-automation/get-started/get_api_token.html["Documentazione di Astra Automation"^].
. Modificare il file di configurazione di esempio nella directory config/samples del repository dell'operatore di Astra Connector per includere `spec.natssync-client.cloud-bridge-url` chiave. Ad esempio:
+
[listing]
----
apiVersion: netapp.astraconnector.com/v1
kind: AstraConnector
metadata:
  name: astra-connector
spec:
  natssync-client:
    image: natssync-client:2.0
    cloud-bridge-url: https://<your.astra.control.service.url>
  nats:
    image: nats:2.6.1-alpine3.14
  httpproxy-client:
    image: httpproxylet:2.0
  echo-client:
    image: echo-proxylet:2.0
  imageRegistry:
    name: theotw
  astra:
    token: <Astra Control API token>
    clusterName: <your-cluster-name>
    accountId: <Astra Control account id>
    acceptEULA: yes
----
. Applicare il CRD (Custom Resource Definition) di Astra Connector.
+
[source, console]
----
kubectl apply -f config/samples/astraconnector_v1.yaml -n astra-connector
----
. Controllare lo stato del connettore Astra.
+
[source, console]
----
kubectl get astraconnector astra-connector -n astra-connector
----
+
Si consiglia di fare riferimento a un output simile a quanto segue:

+
[source, console]
----
NAME              REGISTERED   ASTRACONNECTORID
astra-connector   true         22b839aa-8b85-445a-85dd-0b1f53b5ea19
----




== Configurare lo storage persistente

Configurare lo storage persistente per il cluster. È possibile utilizzare dischi gestiti da Azure NetApp Files o Azure. Per ulteriori informazioni sulla configurazione di Azure con le seguenti opzioni, consultare la documentazione introduttiva:

* https://docs.netapp.com/us-en/astra-control-service/get-started/set-up-microsoft-azure-with-anf.html["Configurare Microsoft Azure con Azure NetApp Files"]
* https://docs.netapp.com/us-en/astra-control-service/get-started/set-up-microsoft-azure-with-amd.html["Configurare Microsoft Azure con dischi gestiti Azure"]




== Aggiungere il cluster privato ad Astra Control Service

È ora possibile aggiungere il cluster privato ad Astra Control Service. Seguire il flusso di lavoro standard per aggiungere un cluster ad Astra Control Service: https://docs.netapp.com/us-en/astra-control-service/get-started/add-first-cluster.html["Inizia a gestire i cluster Kubernetes da Astra Control Service"].
