---
sidebar: sidebar 
permalink: get-started/register.html 
keywords: BlueXP, sign up, log in, login, register, register for BlueXP, create account, sign up for account, get an account, account, accounts 
summary: Il servizio di controllo Astra è integrato nel servizio di autenticazione di NetApp BlueXP. Iscriviti a BlueXP per poter accedere ad Astra Control Service e agli altri servizi cloud di NetApp. 
---
= Registrati per un account Astra Control Service
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/get-started/


[role="lead"]
Per utilizzare il servizio Astra Control, devi disporre di un account Astra Control Service associato al tuo account NetApp BlueXP. Completa il processo di registrazione ad Astra Control Service e, se non disponi già di un account BlueXP, registrati a BlueXP per accedere ad Astra Control Service.



== Registrati per un account Astra Control

Prima di accedere ad Astra Control Service, è necessario completare un processo di registrazione per ottenere un account Astra Control Service.

Quando utilizzi Astra Control Service, gestirai le tue applicazioni dall'interno di un account. Un account include gli utenti che possono visualizzare e gestire le applicazioni all'interno dell'account, oltre ai dati di fatturazione.

.Fasi
. https://cloud.netapp.com/astra["Visita la pagina Astra Control su BlueXP"^].
. Selezionare *Iscriviti al piano gratuito*.
. Fornire le informazioni richieste nel modulo.
+
Durante la compilazione del modulo, è necessario prendere nota di alcuni elementi importanti:

+
** Il nome e l'indirizzo della tua azienda devono essere precisi perché li verificheremo per soddisfare i requisiti della Global Trade Compliance.
** Il nome dell'account * Astra è il nome dell'account Astra Control Service della tua azienda. Questo nome viene visualizzato nell'interfaccia utente di Astra Control Service. Nota: Se necessario, è possibile creare altri account (fino a 5).
** Nel campo *Indirizzo e-mail aziendale*, se si dispone di un account NetApp BlueXP, immettere qui l'e-mail che si utilizza per tale account. Se non disponi ancora di un account NetApp BlueXP, utilizza l'indirizzo email che inserisci qui quando effettui l'iscrizione ad BlueXP.


. Selezionare *Crea account*.




== Iscriviti a BlueXP

Il servizio di controllo Astra è integrato nel servizio di autenticazione di NetApp BlueXP. Puoi accedere a NetApp BlueXP usando le tue credenziali del sito di supporto BlueXP o NetApp. Se non disponi già di un account NetApp BlueXP o del sito di supporto NetApp, iscriviti a BlueXP per poter accedere al servizio Astra Control e agli altri servizi cloud di NetApp. Se disponi già di un account BlueXP o sul sito di supporto NetApp e hai completato la registrazione, puoi accedere https://astra.netapp.io["Servizio di controllo Astra"^] Utilizzando direttamente le credenziali del sito di supporto BlueXP o NetApp.


TIP: Puoi anche utilizzare il single sign-on per accedere a BlueXP utilizzando le credenziali della directory aziendale (identità federata). Per ulteriori informazioni, visitare il sito https://cloud.netapp.com/help-center["Centro assistenza"^] Quindi selezionare *Cloud Central sign-in options* (Opzioni di accesso Cloud Central).

.Fasi
. Passare a. https://cloud.netapp.com["NetApp BlueXP"^].
. In alto a destra, seleziona *inizia*.
. Selezionare *Registrati*.
. Compila il modulo.
+
Assicurati che il numero di telefono e l'indirizzo e-mail inseriti in questo campo siano gli stessi utilizzati nel modulo di registrazione Astra Control precedente.

. Selezionare *Registrati*.
+

TIP: L'indirizzo email inserito in questi moduli corrisponde al tuo ID utente NetApp BlueXP. Utilizza questo ID utente BlueXP quando effettui l'iscrizione a un nuovo account Astra Control o quando un amministratore Astra Control ti invita a un account Astra Control esistente.

. Attende un'e-mail da NetApp BlueXP. L'e-mail proviene dall'indirizzo saas.support@netapp.com e potrebbe richiedere alcuni minuti per arrivare. Controllare la cartella spam.
. All'arrivo del messaggio, selezionare il collegamento nell'e-mail per verificare l'indirizzo e-mail.


.Risultato
Hai ora un accesso utente BlueXP attivo.

Ora che sei registrato, puoi accedere direttamente a Astra Control usando le tue credenziali BlueXP di https://astra.netapp.io[].
