---
sidebar: sidebar 
permalink: release-notes/known-issues.html 
keywords: bugs, known issues, problems 
summary: 'I problemi noti identificano i problemi che potrebbero impedire l"utilizzo corretto di questa versione del prodotto.' 
---
= Problemi noti
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/release-notes/


[role="lead"]
I problemi noti identificano i problemi che potrebbero impedire l'utilizzo corretto di questa versione del prodotto.

I seguenti problemi noti riguardano la versione corrente:

.Applicazioni
* <<Impossibile definire un'applicazione su uno spazio dei nomi che è stato cancellato e ricreato>>


.Backup, ripristino e clonazione
* <<I cloni delle applicazioni non riescono a utilizzare una versione specifica di PostgreSQL>>
* <<I backup e le snapshot delle applicazioni non vengono eseguiti se la classe volumesnapshotclass viene aggiunta dopo la gestione di un cluster>>
* <<Le operazioni di ripristino in-place alle classi di storage economiche ontap-nas falliscono>>
* <<Il ripristino da un backup quando si utilizza la crittografia in-flight Kerberos può non riuscire>>
* <<I dati di backup rimangono nel bucket dopo l'eliminazione per bucket con criteri di conservazione scaduti>>


.Altri problemi
* <<Le operazioni di gestione dei dati dell'app non riescono e si verificano errori di servizio interni (500) quando Astra Trident è offline>>




== Impossibile definire un'applicazione su uno spazio dei nomi che è stato cancellato e ricreato

Se si definisce un'applicazione con uno spazio dei nomi, si elimina lo spazio dei nomi e si reinstalla l'applicazione nello stesso spazio dei nomi, l'operazione non riesce e viene visualizzato un codice di errore 409. Per definire l'applicazione utilizzando lo spazio dei nomi ricreato, eliminare prima la vecchia istanza dell'applicazione.



== I cloni delle applicazioni non riescono a utilizzare una versione specifica di PostgreSQL

I cloni delle applicazioni all'interno dello stesso cluster si guastano costantemente con il grafico BitNami PostgreSQL 11.5.0. Per clonare correttamente, utilizzare una versione precedente o successiva del grafico.



== I backup e le snapshot delle applicazioni non vengono eseguiti se la classe volumesnapshotclass viene aggiunta dopo la gestione di un cluster

In questo scenario, i backup e le snapshot non vengono eseguiti correttamente e viene visualizzato un errore UI 500. Come soluzione, aggiornare l'elenco delle applicazioni.



== Le operazioni di ripristino in-place alle classi di storage economiche ontap-nas falliscono

Se si esegue un ripristino sul posto di un'applicazione (ripristinando l'applicazione nello spazio dei nomi originale) e la classe di archiviazione dell'applicazione utilizza `ontap-nas-economy` driver, l'operazione di ripristino può non riuscire se la directory dello snapshot non è nascosta. Prima di eseguire il ripristino sul posto, seguire le istruzioni riportate in link:../use/protect-apps.html#enable-backup-and-restore-for-ontap-nas-economy-operations["Abilita backup e ripristino per le operazioni economiche a ontap-nas"^] per nascondere la directory dell'istantanea.



== Il ripristino da un backup quando si utilizza la crittografia in-flight Kerberos può non riuscire

Quando si ripristina un'applicazione da un backup a un backend di storage che utilizza la crittografia in-flight Kerberos, l'operazione di ripristino potrebbe non riuscire. Questo problema non influisce sul ripristino da uno snapshot o sulla replica dei dati dell'applicazione tramite SnapMirror di NetApp.


NOTE: Quando si utilizza la crittografia in-flight Kerberos con volumi NFSv4, assicurarsi che i volumi NFSv4 stiano utilizzando le impostazioni corrette. Consultare la sezione Configurazione di dominio NetApp NFSv4 (pagina 13) della https://www.netapp.com/media/16398-tr-3580.pdf["Guida ai miglioramenti e alle Best practice di NetApp NFSv4"^].



== I dati di backup rimangono nel bucket dopo l'eliminazione per bucket con criteri di conservazione scaduti

Se elimini il backup immutabile di un'app dopo che il criterio di conservazione del bucket è scaduto, il backup viene eliminato da Astra Control ma non dal bucket. Questo problema verrà risolto in una prossima release.



== Le operazioni di gestione dei dati dell'app non riescono e si verificano errori di servizio interni (500) quando Astra Trident è offline

Se Astra Trident su un cluster di applicazioni diventa offline (e viene riportato online) e si verificano 500 errori di servizio interni durante il tentativo di gestione dei dati dell'applicazione, riavviare tutti i nodi Kubernetes nel cluster di applicazioni per ripristinare la funzionalità.
